# Generated by Django 4.2.3 on 2023-07-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="author",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
